#!/usr/bin/env python3
import sys
try:
    a = int(sys.argv[1])
    b = a - 3500

    if b > 80000:
        c = b * 0.45 - 13550
    elif b > 55000:
        c = b * 0.35 - 5505
    elif b > 35000:
        c = b * 0.3 - 2755
    elif b > 9000:
        c = b * 0.25 - 1005
    elif b > 4500:
        c = b * 0.2 - 555
    elif b > 1500:
        c = b * 0.1 - 105
    else:
        c = b * 0.3
    print("{:.2f}".format(c))
except:
    print("Parameter Error")
